# 数据处理、特征工程、特征选择

In [1]:
# import 工具库
import pandas as pd

### 载入数据

In [2]:
# Titanic数据
df_train = pd.read_csv('train.csv')

### 了解一下数据
* head()
* info()
* describe()

In [3]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df_train.shape

(891, 12)

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [7]:
df_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## 基本数据处理

### 0.缺失值处理
* pandas fillna
* sklearn Imputer

#### 可以用pandas的fillna函数

In [8]:
# 查询fillna函数
help(pd.DataFrame.fillna)

Help on method fillna in module pandas.core.frame:

fillna(self, value=None, method=None, axis=None, inplace=False, limit=None, downcast=None, **kwargs) unbound pandas.core.frame.DataFrame method
    Fill NA/NaN values using the specified method
    
    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame). (values not
        in the dict/Series/DataFrame will not be filled). This value cannot
        be a list.
    method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series
        pad / ffill: propagate last valid observation forward to next valid
        backfill / bfill: use NEXT valid observation to fill gap
    axis : {0 or 'index', 1 or 'columns'}
    inplace : boolean, default False
        If True, f

In [12]:
df_train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
df_train['Age'].fillna(value=df_train['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.699118
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.699118
18     31.000000
19     29.699118
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.699118
27     19.000000
28     29.699118
29     29.699118
         ...    
861    21.000000
862    48.000000
863    29.699118
864    24.000000
865    42.000000
866    27.000000
867    31.000000
868    29.699118
869     4.000000
870    26.000000
871    47.000000
872    33.000000
873    47.000000
874    28.000000
875    15.000000
876    20.000000
877    19.000000
878    29.699118
879    56.000000
880    25.000000
881    33.000000
882    22.000000
883    28.000000
884    25.000000
885    39.000000
886    27.000000
887    19.000000
888    29.6991

#### 借助sklearn中的Imputer

In [13]:
from sklearn.preprocessing import Imputer

In [14]:
help(Imputer)

Help on class Imputer in module sklearn.preprocessing.imputation:

class Imputer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <imputation>`.
 |  
 |  Parameters
 |  ----------
 |  missing_values : integer or "NaN", optional (default="NaN")
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For missing values encoded as np.nan,
 |      use the string value "NaN".
 |  
 |  strategy : string, optional (default="mean")
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values using the mean along
 |        the axis.
 |      - If "median", then replace missing values using the median along
 |        the axis.
 |      - If "most_frequent", then replace missing using the most frequent
 |        value along the axis.
 |  
 |  axis : integer, optional (default=0)
 |      The axis along which to i

In [15]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)

In [17]:
age = imp.fit_transform(df_train[['Age']].values)

In [18]:
df_train.loc[:,'Age'] = df_train['Age'].fillna(value=df_train['Age'].mean())

In [19]:
df_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex        Age  \
0                            Braund, Mr. Owen Harris    male  22.000000   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                             Heikkinen, Miss. Laina  female  26.000000   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                           Allen, Mr. William Henry    male  35.000000   
5                                   Moran, Mr. James    male  29.699118   
6                            McCarthy, Mr. Timothy J    male  54.000000   
7                     Palsson, Master. Gosta Leonard    male   2.000000   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S  
5      0      0            330877   8.4583   NaN        Q  
6      0      0             17463  51.8625   E46        S  
7      3      1            349909  21.0750   NaN        S  
8      0      2            347742  11.1333   NaN        S  
9      1      0            237736  30.0708   NaN        C

In [20]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


## 常见的特征工程操作

### 数值型

### 0.幅度变换
* apply+numpy
* preprocessing scaler

In [21]:
# 取对数等变换
import numpy as np
log_age = df_train['Age'].apply(lambda x:np.log(x))

In [23]:
df_train.loc[:,'log_age'] = log_age

In [24]:
df_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex        Age  \
0                            Braund, Mr. Owen Harris    male  22.000000   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                             Heikkinen, Miss. Laina  female  26.000000   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                           Allen, Mr. William Henry    male  35.000000   
5                                   Moran, Mr. James    male  29.699118   
6                            McCarthy, Mr. Timothy J    male  54.000000   
7                     Palsson, Master. Gosta Leonard    male   2.000000   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   

   SibSp  Parch            Ticket     Fare Cabin Embarked   log_age  
0      1      0         A/5 21171   7.2500   NaN        S  3.091042  
1      1      0          PC 17599  71.2833   C85        C  3.637586  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  3.258097  
3      1      0            113803  53.1000  C123        S  3.555348  
4      0      0            373450   8.0500   NaN        S  3.555348  
5      0      0            330877   8.4583   NaN        Q  3.391117  
6      0      0             17463  51.8625   E46        S  3.988984  
7      3      1            349909  21.0750   NaN        S  0.693147  
8      0      2            347742  11.1333   NaN        S  3.295837  
9      1      0            237736  30.0708   NaN        C  2.639057

In [25]:
# 幅度缩放，最大最小值缩放
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
fare_trans = mm_scaler.fit_transform(df_train[['Fare']])

In [27]:
# 幅度缩放，标准化
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
fare_std_trans = std_scaler.fit_transform(df_train[['Fare']])

### 1.统计值
* max,min
* quantile

In [29]:
# 最大最小值
max_age = df_train['Age'].max()
min_age = df_train["Age"].min()

In [30]:
max_age

80.0

In [31]:
min_age

0.42

In [32]:
# 分位数
age_quarter_1 = df_train['Age'].quantile(0.25)
age_quarter_3 = df_train['Age'].quantile(0.75)

In [33]:
age_quarter_1

22.0

In [34]:
age_quarter_3

35.0

### 2.四则运算

In [35]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  
0      0         A/5 21171   7.2500   NaN        S  3.091042  
1      0          PC 17599  71.2833   C85        C  3.637586  
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097  
3      0            113803  53.1000  C123        S  3.555348  
4      0            373450   8.0500   NaN        S  3.555348

In [38]:
df_train.loc[:,'family_size'] = df_train['SibSp']+df_train['Parch']+1

In [39]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  
0      0         A/5 21171   7.2500   NaN        S  3.091042            2  
1      0          PC 17599  71.2833   C85        C  3.637586            2  
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1  
3      0            113803  53.1000  C123        S  3.555348            2  
4      0            373450   8.0500   NaN        S  3.555348            1

In [40]:
df_train.loc[:,'tmp'] = df_train['Age']*df_train['Pclass'] + 4*df_train['family_size']

In [41]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  \
0      0         A/5 21171   7.2500   NaN        S  3.091042            2   
1      0          PC 17599  71.2833   C85        C  3.637586            2   
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1   
3      0            113803  53.1000  C123        S  3.555348            2   
4      0            373450   8.0500   NaN        S  3.555348            1   

     tmp  
0   74.0  
1   46.0  
2   82.0  
3   43.0  
4  109.0

### 3.高次特征与交叉特征
* preprocessing.PolynomialFeatures

[x1 x2 x3] => [x1^2 x3^3 x1\*x2 x1\*x3]

In [42]:
from sklearn.preprocessing import PolynomialFeatures

In [43]:
poly = PolynomialFeatures(degree=2)

In [44]:
df_train[['SibSp','Parch']].head()

SibSp  Parch
0      1      0
1      1      0
2      0      0
3      1      0
4      0      0

In [45]:
poly_fea = poly.fit_transform(df_train[['SibSp','Parch']])

In [46]:
poly_fea

array([[1., 1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [1., 1., 2., 1., 2., 4.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

### 4.离散化/分箱/分桶
* pandas cut
* pandas qcut

In [47]:
# 等距切分
df_train.loc[:, 'fare_cut'] = pd.cut(df_train['Fare'], 5)

In [48]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  \
0      0         A/5 21171   7.2500   NaN        S  3.091042            2   
1      0          PC 17599  71.2833   C85        C  3.637586            2   
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1   
3      0            113803  53.1000  C123        S  3.555348            2   
4      0            373450   8.0500   NaN        S  3.555348            1   

     tmp           fare_cut  
0   74.0  (-0.512, 102.466]  
1   46.0  (-0.512, 102.466]  
2   82.0  (-0.512, 102.466]  
3   43.0  (-0.512, 102.466]  
4  109.0  (-0.512, 102.466]

In [49]:
df_train['fare_cut'].unique()

[(-0.512, 102.466], (204.932, 307.398], (102.466, 204.932], (409.863, 512.329]]
Categories (4, interval[float64]): [(-0.512, 102.466] < (102.466, 204.932] < (204.932, 307.398] < (409.863, 512.329]]

In [50]:
# 等频切分
df_train.loc[:,'fare_qcut'] = pd.qcut(df_train['Fare'], 5)

In [51]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  \
0      0         A/5 21171   7.2500   NaN        S  3.091042            2   
1      0          PC 17599  71.2833   C85        C  3.637586            2   
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1   
3      0            113803  53.1000  C123        S  3.555348            2   
4      0            373450   8.0500   NaN        S  3.555348            1   

     tmp           fare_cut          fare_qcut  
0   74.0  (-0.512, 102.466]    (-0.001, 7.854]  
1   46.0  (-0.512, 102.466]  (39.688, 512.329]  
2   82.0  (-0.512, 102.466]      (7.854, 10.5]  
3   43.0  (-0.512, 102.466]  (39.688, 512.329]  
4  109.0  (-0.512, 102.466]      (7.854, 10.5]

### 5.OneHot encoding/独热向量编码
* pandas get_dummies
* OneHotEncoder()

In [52]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
log_age        891 non-null float64
family_size    891 non-null int64
tmp            891 non-null float64
fare_cut       891 non-null category
fare_qcut      891 non-null category
dtypes: category(2), float64(4), int64(6), object(5)
memory usage: 106.4+ KB


In [53]:
embarked_oht = pd.get_dummies(df_train[['Embarked']])

In [55]:
embarked_oht.head()

Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [56]:
fare_qcut_oht = pd.get_dummies(df_train[['fare_qcut']])

In [58]:
fare_qcut_oht.head()

fare_qcut_(-0.001, 7.854]  fare_qcut_(7.854, 10.5]  \
0                          1                        0   
1                          0                        0   
2                          0                        1   
3                          0                        0   
4                          0                        1   

   fare_qcut_(10.5, 21.679]  fare_qcut_(21.679, 39.688]  \
0                         0                           0   
1                         0                           0   
2                         0                           0   
3                         0                           0   
4                         0                           0   

   fare_qcut_(39.688, 512.329]  
0                            0  
1                            1  
2                            0  
3                            1  
4                            0

## 时间型

### 6.日期处理
* pandas to_datetime

In [59]:
car_sales = pd.read_csv('car_data.csv')

In [60]:
car_sales.head()

date_t     cnt
0  2012-12-31     NaN
1  2013-01-01     NaN
2  2013-01-02    68.0
3  2013-01-03    36.0
4  2013-01-04  5565.0

In [61]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 2 columns):
date_t    1512 non-null object
cnt       1032 non-null float64
dtypes: float64(1), object(1)
memory usage: 23.7+ KB


In [62]:
car_sales.describe()

cnt
count  1032.000000
mean   1760.124031
std    1153.164214
min      12.000000
25%    1178.750000
50%    1774.000000
75%    2277.750000
max    7226.000000

In [63]:
car_sales['date_t'].dtype

dtype('O')

In [64]:
car_sales.loc[:,'date'] = pd.to_datetime(car_sales['date_t'])

In [65]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 3 columns):
date_t    1512 non-null object
cnt       1032 non-null float64
date      1512 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 35.5+ KB


In [66]:
car_sales.head()

date_t     cnt       date
0  2012-12-31     NaN 2012-12-31
1  2013-01-01     NaN 2013-01-01
2  2013-01-02    68.0 2013-01-02
3  2013-01-03    36.0 2013-01-03
4  2013-01-04  5565.0 2013-01-04

### 7.取出关键时间信息
* .dt.month
* .dt.dayofweek
* .dt.dayofyear
* ...

In [67]:
# 取出几月份
car_sales.loc[:,'month'] = car_sales['date'].dt.month

In [68]:
car_sales.head()

date_t     cnt       date  month
0  2012-12-31     NaN 2012-12-31     12
1  2013-01-01     NaN 2013-01-01      1
2  2013-01-02    68.0 2013-01-02      1
3  2013-01-03    36.0 2013-01-03      1
4  2013-01-04  5565.0 2013-01-04      1

In [69]:
tmp_date = car_sales['date'].dt

In [74]:
# 取出来是几号
car_sales.loc[:,'dom'] = car_sales['date'].dt.day

In [75]:
# 取出一年当中的第几天
car_sales.loc[:,'doy'] = car_sales['date'].dt.dayofyear

In [77]:
# 取出星期几
car_sales.loc[:,'dow'] = car_sales['date'].dt.dayofweek

In [78]:
car_sales.head()

date_t     cnt       date  month  dom  doy  dow
0  2012-12-31     NaN 2012-12-31     12   31  366    0
1  2013-01-01     NaN 2013-01-01      1    1    1    1
2  2013-01-02    68.0 2013-01-02      1    2    2    2
3  2013-01-03    36.0 2013-01-03      1    3    3    3
4  2013-01-04  5565.0 2013-01-04      1    4    4    4

In [79]:
car_sales.loc[:,'is_weekend'] = car_sales['dow'].apply(lambda x: 1 if (x==0 or x==6) else 0)

In [80]:
car_sales.head()

date_t     cnt       date  month  dom  doy  dow  is_weekend
0  2012-12-31     NaN 2012-12-31     12   31  366    0           1
1  2013-01-01     NaN 2013-01-01      1    1    1    1           0
2  2013-01-02    68.0 2013-01-02      1    2    2    2           0
3  2013-01-03    36.0 2013-01-03      1    3    3    3           0
4  2013-01-04  5565.0 2013-01-04      1    4    4    4           0

## 文本型

### 8.词袋模型
* CountVectorizer

In [81]:
from sklearn.feature_extraction.text import CountVectorizer

In [82]:
vectorizer = CountVectorizer()

In [88]:
corpus = [
    'This is a very good class',
    'students are very very very good',
    'This is the third sentence',
    'Is this the last doc'
]

In [89]:
X = vectorizer.fit_transform(corpus)

In [90]:
X

<4x12 sparse matrix of type '<type 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [91]:
vectorizer.get_feature_names()

[u'are',
 u'class',
 u'doc',
 u'good',
 u'is',
 u'last',
 u'sentence',
 u'students',
 u'the',
 u'third',
 u'this',
 u'very']

In [92]:
X.toarray()

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 3],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0]])

In [93]:
vec = CountVectorizer(ngram_range=(1,3))

In [94]:
X_ngram = vec.fit_transform(corpus)

In [96]:
vec.get_feature_names()

[u'are',
 u'are very',
 u'are very very',
 u'class',
 u'doc',
 u'good',
 u'good class',
 u'is',
 u'is the',
 u'is the third',
 u'is this',
 u'is this the',
 u'is very',
 u'is very good',
 u'last',
 u'last doc',
 u'sentence',
 u'students',
 u'students are',
 u'students are very',
 u'the',
 u'the last',
 u'the last doc',
 u'the third',
 u'the third sentence',
 u'third',
 u'third sentence',
 u'this',
 u'this is',
 u'this is the',
 u'this is very',
 u'this the',
 u'this the last',
 u'very',
 u'very good',
 u'very good class',
 u'very very',
 u'very very good',
 u'very very very']

In [95]:
X_ngram.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 2, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]])

### 9.TF-IDF
* TfidfVectorizer

In [97]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [98]:
tfidf_vec = TfidfVectorizer()

In [99]:
tfidf_X = tfidf_vec.fit_transform(corpus)

In [100]:
tfidf_vec.get_feature_names()

[u'are',
 u'class',
 u'doc',
 u'good',
 u'is',
 u'last',
 u'sentence',
 u'students',
 u'the',
 u'third',
 u'this',
 u'very']

In [101]:
tfidf_X.toarray()

array([[0.        , 0.57184829, 0.        , 0.45085176, 0.36500336,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.36500336, 0.45085176],
       [0.3488765 , 0.        , 0.        , 0.27505824, 0.        ,
        0.        , 0.        , 0.3488765 , 0.        , 0.        ,
        0.        , 0.82517473],
       [0.        , 0.        , 0.        , 0.        , 0.34432086,
        0.        , 0.53944516, 0.        , 0.42530476, 0.53944516,
        0.34432086, 0.        ],
       [0.        , 0.        , 0.53944516, 0.        , 0.34432086,
        0.53944516, 0.        , 0.        , 0.42530476, 0.        ,
        0.34432086, 0.        ]])

### 10.组合特征

In [102]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  \
0      0         A/5 21171   7.2500   NaN        S  3.091042            2   
1      0          PC 17599  71.2833   C85        C  3.637586            2   
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1   
3      0            113803  53.1000  C123        S  3.555348            2   
4      0            373450   8.0500   NaN        S  3.555348            1   

     tmp           fare_cut          fare_qcut  
0   74.0  (-0.512, 102.466]    (-0.001, 7.854]  
1   46.0  (-0.512, 102.466]  (39.688, 512.329]  
2   82.0  (-0.512, 102.466]      (7.854, 10.5]  
3   43.0  (-0.512, 102.466]  (39.688, 512.329]  
4  109.0  (-0.512, 102.466]      (7.854, 10.5]

In [103]:
# 借助条件去判断获取组合特征
df_train.loc[:,'alone'] = (df_train['SibSp']==0)&(df_train['Parch']==0)

In [104]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   log_age  family_size  \
0      0         A/5 21171   7.2500   NaN        S  3.091042            2   
1      0          PC 17599  71.2833   C85        C  3.637586            2   
2      0  STON/O2. 3101282   7.9250   NaN        S  3.258097            1   
3      0            113803  53.1000  C123        S  3.555348            2   
4      0            373450   8.0500   NaN        S  3.555348            1   

     tmp           fare_cut          fare_qcut  alone  
0   74.0  (-0.512, 102.466]    (-0.001, 7.854]  False  
1   46.0  (-0.512, 102.466]  (39.688, 512.329]  False  
2   82.0  (-0.512, 102.466]      (7.854, 10.5]   True  
3   43.0  (-0.512, 102.466]  (39.688, 512.329]  False  
4  109.0  (-0.512, 102.466]      (7.854, 10.5]   True

## 特征选择

### 过滤式/Filter
* SelectKBest

In [105]:
from sklearn.feature_selection import SelectKBest
from sklearn.datasets import load_iris

In [106]:
iris = load_iris()

In [109]:
X, y = iris.data, iris.target

In [110]:
X.shape

(150, 4)

In [112]:
X[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [113]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [114]:
X_new = SelectKBest(k=2).fit_transform(X,y)

In [115]:
X_new.shape

(150, 2)

In [117]:
X_new[:5,:]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

### 包裹型/wrapper
* RFE

In [118]:
from sklearn.feature_selection import RFE

In [119]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [120]:
rfe = RFE(estimator=rf, n_features_to_select=2)

In [121]:
X_rfe = rfe.fit_transform(X,y)

In [123]:
X_rfe.shape

(150, 2)

In [124]:
X_rfe[:5,:]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

### 嵌入式/Embedded
* SelectFromModel

In [125]:
from sklearn.feature_selection import SelectFromModel

In [126]:
from sklearn.svm import LinearSVC

In [127]:
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X,y)

In [128]:
model = SelectFromModel(lsvc, prefit=True)

In [129]:
X_embed = model.transform(X)

In [130]:
X_embed.shape

(150, 3)

In [131]:
X_embed[:5,:]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])