In [3]:
# 载入所需要的库
import numpy as np
import pandas as pd
# 载入数据
X_test = pd.read_pickle('./input/X_test.pkl')
X_train = pd.read_pickle('./input/X_train.pkl')
y_train = pd.read_pickle('./input/y_train.pkl')

In [4]:
from sklearn.preprocessing import minmax_scale as mm
X_test = mm(X_test)
X_train= mm(X_train)

In [5]:
X_train

array([[  0.00000000e+00,   2.85828332e-02,   1.65071081e-01, ...,
          4.54176206e-03,   1.89633912e-01,   1.14260390e-01],
       [  1.09541023e-04,   2.89064679e-02,   2.04216322e-01, ...,
          8.30810132e-03,   1.16149868e-01,   1.70142144e-01],
       [  2.19082046e-04,   9.77677619e-01,   3.78936225e-01, ...,
          1.47071856e-02,   2.25840692e-03,   2.25304306e-01],
       ..., 
       [  9.99890459e-01,   5.77678074e-01,   2.71296831e-01, ...,
          4.41873242e-02,   1.36074265e-01,   2.14085323e-01],
       [  1.00000000e+00,   5.82892751e-01,   1.81981292e-01, ...,
          7.05265490e-03,   1.51200343e-01,   1.44882848e-01],
       [  4.96465444e-01,   4.93740506e-01,   5.63497516e-03, ...,
          8.12347685e-03,   4.94591115e-03,   3.91082327e-03]])

In [1]:
import sklearn.preprocessing as pp

In [2]:
help(pp)

Help on package sklearn.preprocessing in sklearn:

NAME
    sklearn.preprocessing

FILE
    /usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/__init__.py

DESCRIPTION
    The :mod:`sklearn.preprocessing` module includes scaling, centering,
    normalization, binarization and imputation methods.

PACKAGE CONTENTS
    _function_transformer
    data
    imputation
    label
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(__builtin__.object)
        sklearn.preprocessing._function_transformer.FunctionTransformer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
        sklearn.preprocessing.data.Binarizer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
        sklearn.preprocessing.data.KernelCenterer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
        sklearn.preprocessing.data.MaxAbsScaler(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
        sklearn.preprocessing.data.MinMaxScaler(sklearn.base.BaseEstimator, sklearn.

## 逻辑回归

In [3]:
import warnings 
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# 一个训练优化模型的函数
def train_optimal_classifier(clf,param):
    grid_search = GridSearchCV(
        clf,
        param_grid=param,
        cv=5,
        verbose=0,
        scoring='f1_weighted',
        error_score=0,
        refit=True ,
        n_jobs=-1
        )
    grid_search.fit(X_train, y_train)
    print("Best parameters")
    print(grid_search.best_params_)
    print('best F1: ')
    print(grid_search.best_score_)
    return (grid_search.best_estimator_)


LR = LogisticRegression(class_weight='balanced',random_state=33,n_jobs=-1,solver='lbfgs')

param_LR = {  "C":[2e4,5e4,1e5,2e5,4e5,8e5],
             }
LR_best = train_optimal_classifier(LR,param_LR)

Best parameters
{'C': 400000.0}
best F1: 
0.519738544816


In [4]:
LR_best.fit(X_train, y_train)
y_pred = LR_best.predict(X_test)

In [5]:
y_pred

array([2000, 2000, 2000, ...,    0,    0,    0])

In [6]:
data =  pd.read_csv("./input/studentID_test.txt", names=['学生id','助学金金额'], encoding='utf-8')

In [7]:
data['助学金金额'] = pd.DataFrame(y_pred)
data.to_csv('./Result/LR_Result.csv')

## Bagging 逻辑回归

In [8]:
from sklearn.ensemble import BaggingClassifier
BC = BaggingClassifier(LR_best)
param = {}
Model_best = train_optimal_classifier(BC,param)

Best parameters
{}
best F1: 
0.521060759378


In [9]:
Model_best.fit(X_train, y_train)
y_pred = Model_best.predict(X_test)

In [10]:
y_pred

array([2000, 1000, 2000, ...,    0,    0,    0])

In [11]:
data['助学金金额'] = pd.DataFrame(y_pred)
data.to_csv('./Result/Bagging_Result.csv')